### ISSUE TITLE
Fix clippy warnings

### ISSUE THREAD

**Issue by lzutao** [matthiasbeyer/toml-query#44]
Generate clippy warnings by
```bash
rustup component add clippy
cargo clippy --all --all-targets
```

**Comment by matthiasbeyer** [comment]
Can you please provide an example how you generated these warnings?

**Comment by lzutao** [comment]
I added it.

**Comment by matthiasbeyer** [comment]
I would like you to provide patches for this, because I'm loaded with work this and next week, so if it is urgent for you, please send patches.

_Maybe_ I can have a look this weekend, but I cannot promise anything.

If you provide patches, feel free to also add a travis job (non-failing until everything is fixed) that runs clippy on the sources. Maybe even add another job that does rustfmt (also non-failing).
